In [79]:
import numpy as np

# Example
<strong>Review 1:</strong> This movie is very scary and long <br/>
<strong>Review 2:</strong> This movie is not scary and is slow <br/>
<strong>Review 3:</strong> This movie is spooky and good <br/>

In [45]:
allsentences = ["This movie is very scary and long", "This movie is not scary and is slow", "This movie is spooky and good"]

# Tokenize a sentence

In [97]:
def word_extraction(sentence):    
    words = sentence.split()    
    words = [w.lower() for w in words]    
    return words

In [87]:
word_extraction(allsentences[0])

['this', 'movie', 'is', 'very', 'scary', 'and', 'long']

In [63]:
def tokenize(sentences):    
    words = []    
    for sentence in sentences:        
        w = word_extraction(sentence)        
        words.extend(w)            
    words = sorted(list(set(words)))    
    return words

# Generate the vocabulary

In [93]:
def generate_bow(allsentences):        
    vocab = sorted(tokenize(allsentences))
    return vocab

In [98]:
vocab = generate_bow(allsentences)
print("the vocabulary : \n{0}".format(vocab))

the vocabulary : 
['and', 'good', 'is', 'long', 'movie', 'not', 'scary', 'slow', 'spooky', 'this', 'very']


In [99]:
matrix_representation = np.zeros((len(allsentences),len(vocab)))

In [100]:

for j,sentence in enumerate(allsentences):
    words = word_extraction(sentence)
    for word in words:
        index = vocab.index(word)
        matrix_representation[j,index] += 1 

print("Text Representation : ")
print("{0}\n".format(np.array(matrix_representation)))
print(allsentences)

Text Representation : 
[[1. 0. 1. 1. 1. 0. 1. 0. 0. 1. 1.]
 [1. 0. 2. 0. 1. 1. 1. 1. 0. 1. 0.]
 [1. 1. 1. 0. 1. 0. 0. 0. 1. 1. 0.]]

['This movie is very scary and long', 'This movie is not scary and is slow', 'This movie is spooky and good']


In [101]:
dict(zip(vocab,range(len(vocab))))

{'and': 0,
 'good': 1,
 'is': 2,
 'long': 3,
 'movie': 4,
 'not': 5,
 'scary': 6,
 'slow': 7,
 'spooky': 8,
 'this': 9,
 'very': 10}

# Bag-of-words in sklearn

In [102]:
from sklearn.feature_extraction.text import CountVectorizer

In [103]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(allsentences).toarray()
X

array([[1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1],
       [1, 0, 2, 0, 1, 1, 1, 1, 0, 1, 0],
       [1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0]], dtype=int64)